
spring:
  application:
    name: graduationdesign
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/graduationdesign?useUnicode=true&characterEncoding=UTF-8
    password: root
    username: root
server:
  port: 8003
